package br.com.pointel.wiz_jarch.data;

import java.sql.Connection;

public class EOrmFirebird extends EOrmBase {

    public EOrmFirebird(Connection link) {
        super(link);
    }

    @Override
    protected String makeNature(Field field) {
        var builder = new StringBuilder(field.name);
        switch (field.nature) {
            case Bool: builder.append(" BOOLEAN"); break;
            case Bit, Byte, Tiny, Small: builder.append(" SMALLINT"); break;
            case Int: builder.append(" INTEGER"); break;
            case BigInt, Long: builder.append(" BIGINT"); break;
            case Serial: builder.append(" INTEGER GENERATED BY DEFAULT AS IDENTITY"); break;
            case BigSerial: builder.append(" BIGINT GENERATED BY DEFAULT AS IDENTITY"); break;
            case Float, Real: builder.append(" FLOAT"); break;
            case Double: builder.append(" DOUBLE PRECISION"); break;
            case Numeric, BigNumeric:
                builder.append(" NUMERIC");
                if (field.size != null) {
                    builder.append("(").append(field.size);
                    if (field.precision != null) {
                        builder.append(",").append(field.precision);
                    }
                    builder.append(")");
                }
                break;
            case Char: builder.append(" CHAR(1)"); break;
            case Chars:
                builder.append(" VARCHAR");
                if (field.size != null) {
                    builder.append("(").append(field.size).append(")");
                }
                break;
            case Date: builder.append(" DATE"); break;
            case Time: builder.append(" TIME"); break;
            case DateTime, ZoneTime, Timestamp: builder.append(" TIMESTAMP"); break;
            case Bytes, Blob, Object: 
                builder.append(" BLOB"); 
                break;
            case Text: 
                builder.append(" BLOB SUB_TYPE TEXT"); 
                break;
            default:
                throw new UnsupportedOperationException();
        }
        if (Boolean.TRUE.equals(field.notNull)) {
            builder.append(" NOT NULL");
        }
        return builder.toString();
    }
}
