package br.com.pointel.wiz_jarch.data;

import br.com.pointel.wiz_jarch.mage.WizData;

/**
 * Describes a table field, including its type, constraints, and cached table
 * reference.
 */
public class Field implements Data {

    public Integer ord;
    public String name;
    public Nature nature;
    public Integer size;
    public Integer precision;
    public Boolean notNull;
    public Boolean autoIncrement;
    public Boolean autoGenerated;
    public Boolean keyPrimary;

    /**
     * Cached table reference for qualified field names.
     */
    private transient Table table;

    /**
     * Creates an empty field descriptor.
     */
    public Field() {
    }

    /**
     * Creates a field descriptor with the given name.
     *
     * @param name the field name
     */
    public Field(String name) {
        this.name = name;
    }

    /**
     * Creates a field descriptor with the given order and name.
     *
     * @param ord the field order
     * @param name the field name
     */
    public Field(Integer ord, String name) {
        this.ord = ord;
        this.name = name;
    }

    /**
     * Creates a field descriptor with the given name and type.
     *
     * @param name the field name
     * @param nature the field type
     */
    public Field(String name, Nature nature) {
        this.name = name;
        this.nature = nature;
    }

    /**
     * Creates a field descriptor with the given order, name, and type.
     *
     * @param ord the field order
     * @param name the field name
     * @param nature the field type
     */
    public Field(Integer ord, String name, Nature nature) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
    }

    /**
     * Creates a field descriptor with the given name, type, and nullability.
     *
     * @param name the field name
     * @param nature the field type
     * @param notNull whether the field is required
     */
    public Field(String name, Nature nature, Boolean notNull) {
        this.name = name;
        this.nature = nature;
        this.notNull = notNull;
    }

    /**
     * Creates a field descriptor with the given order, name, type, and nullability.
     *
     * @param ord the field order
     * @param name the field name
     * @param nature the field type
     * @param notNull whether the field is required
     */
    public Field(Integer ord, String name, Nature nature, Boolean notNull) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.notNull = notNull;
    }

    /**
     * Creates a field descriptor with the given primary-key flag.
     *
     * @param name the field name
     * @param nature the field type
     * @param notNull whether the field is required
     * @param keyPrimary whether the field is part of the primary key
     */
    public Field(String name, Nature nature, Boolean notNull, Boolean keyPrimary) {
        this.name = name;
        this.nature = nature;
        this.notNull = notNull;
        this.keyPrimary = keyPrimary;
    }

    /**
     * Creates a field descriptor with order and primary-key flag.
     *
     * @param ord the field order
     * @param name the field name
     * @param nature the field type
     * @param notNull whether the field is required
     * @param keyPrimary whether the field is part of the primary key
     */
    public Field(Integer ord, String name, Nature nature, Boolean notNull, Boolean keyPrimary) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.notNull = notNull;
        this.keyPrimary = keyPrimary;
    }

    /**
     * Creates a field descriptor with size information.
     *
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     */
    public Field(String name, Nature nature, Integer size) {
        this.name = name;
        this.nature = nature;
        this.size = size;
    }

    /**
     * Creates a field descriptor with order and size information.
     *
     * @param ord the field order
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     */
    public Field(Integer ord, String name, Nature nature, Integer size) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
    }

    /**
     * Creates a field descriptor with size and nullability information.
     *
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param notNull whether the field is required
     */
    public Field(String name, Nature nature, Integer size, Boolean notNull) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.notNull = notNull;
    }

    /**
     * Creates a field descriptor with order, size, and nullability information.
     *
     * @param ord the field order
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param notNull whether the field is required
     */
    public Field(Integer ord, String name, Nature nature, Integer size, Boolean notNull) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.notNull = notNull;
    }

    /**
     * Creates a field descriptor with size and precision information.
     *
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param precision the precision value
     */
    public Field(String name, Nature nature, Integer size, Integer precision) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
    }

    /**
     * Creates a field descriptor with order, size, and precision information.
     *
     * @param ord the field order
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param precision the precision value
     */
    public Field(Integer ord, String name, Nature nature, Integer size, Integer precision) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
    }

    /**
     * Creates a field descriptor with size, precision, and nullability information.
     *
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param precision the precision value
     * @param notNull whether the field is required
     */
    public Field(String name, Nature nature, Integer size, Integer precision, Boolean notNull) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
    }

    /**
     * Creates a field descriptor with order, size, precision, and nullability information.
     *
     * @param ord the field order
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param precision the precision value
     * @param notNull whether the field is required
     */
    public Field(Integer ord, String name, Nature nature, Integer size, Integer precision, Boolean notNull) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
    }

    /**
     * Creates a field descriptor with size, precision, nullability, and primary-key flag.
     *
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param precision the precision value
     * @param notNull whether the field is required
     * @param keyPrimary whether the field is part of the primary key
     */
    public Field(String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean keyPrimary) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.keyPrimary = keyPrimary;
    }

    /**
     * Creates a field descriptor with order, size, precision, nullability, and primary-key flag.
     *
     * @param ord the field order
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param precision the precision value
     * @param notNull whether the field is required
     * @param keyPrimary whether the field is part of the primary key
     */
    public Field(Integer ord, String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean keyPrimary) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.keyPrimary = keyPrimary;
    }

    /**
     * Creates a field descriptor with all column attributes except order and table.
     *
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param precision the precision value
     * @param notNull whether the field is required
     * @param autoIncrement whether the field auto-increments
     * @param autoGenerated whether the field is generated by the database
     * @param keyPrimary whether the field is part of the primary key
     */
    public Field(String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean autoIncrement, Boolean autoGenerated, Boolean keyPrimary) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.autoIncrement = autoIncrement;
        this.autoGenerated = autoGenerated;
        this.keyPrimary = keyPrimary;
    }

    /**
     * Creates a field descriptor with order and all column attributes except table.
     *
     * @param ord the field order
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param precision the precision value
     * @param notNull whether the field is required
     * @param autoIncrement whether the field auto-increments
     * @param autoGenerated whether the field is generated by the database
     * @param keyPrimary whether the field is part of the primary key
     */
    public Field(Integer ord, String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean autoIncrement, Boolean autoGenerated, Boolean keyPrimary) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.autoIncrement = autoIncrement;
        this.autoGenerated = autoGenerated;
        this.keyPrimary = keyPrimary;
    }

    /**
     * Creates a field descriptor with a cached table reference.
     *
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param precision the precision value
     * @param notNull whether the field is required
     * @param autoIncrement whether the field auto-increments
     * @param autoGenerated whether the field is generated by the database
     * @param keyPrimary whether the field is part of the primary key
     * @param table the owning table
     */
    public Field(String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean autoIncrement, Boolean autoGenerated, Boolean keyPrimary, Table table) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.autoIncrement = autoIncrement;
        this.autoGenerated = autoGenerated;
        this.keyPrimary = keyPrimary;
        this.table = table;
    }

    /**
     * Creates a field descriptor with order and a cached table reference.
     *
     * @param ord the field order
     * @param name the field name
     * @param nature the field type
     * @param size the size or length
     * @param precision the precision value
     * @param notNull whether the field is required
     * @param autoIncrement whether the field auto-increments
     * @param autoGenerated whether the field is generated by the database
     * @param keyPrimary whether the field is part of the primary key
     * @param table the owning table
     */
    public Field(Integer ord, String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean autoIncrement, Boolean autoGenerated, Boolean keyPrimary, Table table) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.autoIncrement = autoIncrement;
        this.autoGenerated = autoGenerated;
        this.keyPrimary = keyPrimary;
        this.table = table;
    }

    /**
     * Indicates whether the order is set.
     *
     * @return {@code true} when the order is non-null; otherwise {@code false}
     */
    public boolean hasOrd() {
        return this.ord != null;
    }

    /**
     * Indicates whether the name is set.
     *
     * @return {@code true} when the name is non-empty; otherwise {@code false}
     */
    public boolean hasName() {
        return this.name != null && !this.name.isEmpty();
    }

    /**
     * Indicates whether the type is set.
     *
     * @return {@code true} when the type is non-null; otherwise {@code false}
     */
    public boolean hasNature() {
        return this.nature != null;
    }

    /**
     * Indicates whether the size is set.
     *
     * @return {@code true} when the size is non-null; otherwise {@code false}
     */
    public boolean hasSize() {
        return this.size != null;
    }

    /**
     * Indicates whether the precision is set.
     *
     * @return {@code true} when the precision is non-null; otherwise {@code false}
     */
    public boolean hasPrecision() {
        return this.precision != null;
    }

    /**
     * Indicates whether nullability is set.
     *
     * @return {@code true} when the nullability flag is non-null; otherwise {@code false}
     */
    public boolean hasNotNull() {
        return this.notNull != null;
    }

    /**
     * Indicates whether the field is required.
     *
     * @return {@code true} when {@link #notNull} is {@code Boolean.TRUE}
     */
    public boolean isNotNull() {
        return Boolean.TRUE.equals(this.notNull);
    }

    /**
     * Indicates whether the field allows null values.
     *
     * @return {@code true} when the field is not explicitly marked as required
     */
    public boolean isNull() {
        return !Boolean.TRUE.equals(this.notNull);
    }

    /**
     * Indicates whether auto-increment metadata is set.
     *
     * @return {@code true} when the flag is non-null; otherwise {@code false}
     */
    public boolean hasAutoIncrement() {
        return this.autoIncrement != null;
    }

    /**
     * Indicates whether the field auto-increments.
     *
     * @return {@code true} when the flag is {@code Boolean.TRUE}
     */
    public boolean isAutoIncrement() {
        return Boolean.TRUE.equals(this.autoIncrement);
    }

    /**
     * Indicates whether the field is not marked as auto-increment.
     *
     * @return {@code true} when auto-increment is not enabled
     */
    public boolean isNotAutoIncrement() {
        return !Boolean.TRUE.equals(this.autoIncrement);
    }

    /**
     * Indicates whether auto-generated metadata is set.
     *
     * @return {@code true} when the flag is non-null; otherwise {@code false}
     */
    public boolean hasAutoGenerated() {
        return this.autoGenerated != null;
    }

    /**
     * Indicates whether the field is auto-generated.
     *
     * @return {@code true} when the flag is {@code Boolean.TRUE}
     */
    public boolean isAutoGenerated() {
        return Boolean.TRUE.equals(this.autoGenerated);
    }

    /**
     * Indicates whether the field is not marked as auto-generated.
     *
     * @return {@code true} when auto-generation is not enabled
     */
    public boolean isNotAutoGenerated() {
        return !Boolean.TRUE.equals(this.autoGenerated);
    }

    /**
     * Indicates whether primary-key metadata is set.
     *
     * @return {@code true} when the flag is non-null; otherwise {@code false}
     */
    public boolean hasKeyPrimary() {
        return this.keyPrimary != null;
    }

    /**
     * Indicates whether the field is part of the primary key.
     *
     * @return {@code true} when the flag is {@code Boolean.TRUE}
     */
    public boolean isKeyPrimary() {
        return Boolean.TRUE.equals(this.keyPrimary);
    }

    /**
     * Indicates whether the field is not part of the primary key.
     *
     * @return {@code true} when primary-key membership is not enabled
     */
    public boolean isNotKeyPrimary() {
        return !Boolean.TRUE.equals(this.keyPrimary);
    }

    /**
     * Indicates whether a table reference is cached.
     *
     * @return {@code true} when a table reference is present; otherwise {@code false}
     */
    public boolean hasTable() {
        return this.table != null;
    }

    /**
     * Updates the field order and returns this descriptor.
     *
     * @param ord the new order
     * @return this descriptor
     */
    public Field withOrd(Integer ord) {
        this.ord = ord;
        return this;
    }

    /**
     * Clears the field order and returns this descriptor.
     *
     * @return this descriptor
     */
    public Field withNoOrd() {
        this.ord = null;
        return this;
    }

    /**
     * Updates the field name and returns this descriptor.
     *
     * @param name the new field name
     * @return this descriptor
     */
    public Field withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Clears the field name and returns this descriptor.
     *
     * @return this descriptor
     */
    public Field withNoName() {
        this.name = null;
        return this;
    }

    /**
     * Updates the field type and returns this descriptor.
     *
     * @param nature the new field type
     * @return this descriptor
     */
    public Field withNature(Nature nature) {
        this.nature = nature;
        return this;
    }

    /**
     * Clears the field type and returns this descriptor.
     *
     * @return this descriptor
     */
    public Field withNoNature() {
        this.nature = null;
        return this;
    }

    /**
     * Updates the size and returns this descriptor.
     *
     * @param size the new size
     * @return this descriptor
     */
    public Field withSize(Integer size) {
        this.size = size;
        return this;
    }

    /**
     * Clears the size and returns this descriptor.
     *
     * @return this descriptor
     */
    public Field withNoSize() {
        this.size = null;
        return this;
    }

    /**
     * Updates the precision and returns this descriptor.
     *
     * @param precision the new precision value
     * @return this descriptor
     */
    public Field withPrecision(Integer precision) {
        this.precision = precision;
        return this;
    }

    /**
     * Clears the precision and returns this descriptor.
     *
     * @return this descriptor
     */
    public Field withNoPrecision() {
        this.precision = null;
        return this;
    }

    /**
     * Updates the nullability flag and returns this descriptor.
     *
     * @param notNull the new nullability flag
     * @return this descriptor
     */
    public Field withNotNull(Boolean notNull) {
        this.notNull = notNull;
        return this;
    }

    /**
     * Clears the nullability flag and returns this descriptor.
     *
     * @return this descriptor
     */
    public Field withNoNotNull() {
        this.notNull = null;
        return this;
    }

    /**
     * Updates the auto-increment flag and returns this descriptor.
     *
     * @param autoIncrement the new auto-increment flag
     * @return this descriptor
     */
    public Field withAutoIncrement(Boolean autoIncrement) {
        this.autoIncrement = autoIncrement;
        return this;
    }

    /**
     * Clears the auto-increment flag and returns this descriptor.
     *
     * @return this descriptor
     */
    public Field withNoAutoIncrement() {
        this.autoIncrement = null;
        return this;
    }

    /**
     * Updates the auto-generated flag and returns this descriptor.
     *
     * @param autoGenerated the new auto-generated flag
     * @return this descriptor
     */
    public Field withAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
        return this;
    }

    /**
     * Clears the auto-generated flag and returns this descriptor.
     *
     * @return this descriptor
     */
    public Field withNoAutoGenerated() {
        this.autoGenerated = null;
        return this;
    }

    /**
     * Updates the primary-key flag and returns this descriptor.
     *
     * @param keyPrimary the new primary-key flag
     * @return this descriptor
     */
    public Field withKeyPrimary(Boolean keyPrimary) {
        this.keyPrimary = keyPrimary;
        return this;
    }

    /**
     * Clears the primary-key flag and returns this descriptor.
     *
     * @return this descriptor
     */
    public Field withNoKeyPrimary() {
        this.keyPrimary = null;
        return this;
    }

    /**
     * Updates the cached table reference and returns this descriptor.
     *
     * @param table the owning table
     * @return this descriptor
     */
    public Field withTable(Table table) {
        this.table = table;
        return this;
    }

    /**
     * Clears the cached table reference and returns this descriptor.
     *
     * @return this descriptor
     */
    public Field withNoTable() {
        this.table = null;
        return this;
    }

    /**
     * Returns a cloned field with the given order.
     *
     * @param ord the replacement order
     * @return a cloned field with the order updated
     */
    public Field uponOrd(Integer ord) {
        Field clone = this.clone();
        clone.ord = ord;
        return clone;
    }

    /**
     * Returns a cloned field without an order.
     *
     * @return a cloned field with the order cleared
     */
    public Field uponNoOrd() {
        Field clone = this.clone();
        clone.ord = null;
        return clone;
    }

    /**
     * Returns a cloned field with the given name.
     *
     * @param name the replacement field name
     * @return a cloned field with the name updated
     */
    public Field uponName(String name) {
        Field clone = this.clone();
        clone.name = name;
        return clone;
    }

    /**
     * Returns a cloned field without a name.
     *
     * @return a cloned field with the name cleared
     */
    public Field uponNoName() {
        Field clone = this.clone();
        clone.name = null;
        return clone;
    }

    /**
     * Returns a cloned field with the given type.
     *
     * @param nature the replacement field type
     * @return a cloned field with the type updated
     */
    public Field uponNature(Nature nature) {
        Field clone = this.clone();
        clone.nature = nature;
        return clone;
    }

    /**
     * Returns a cloned field without a type.
     *
     * @return a cloned field with the type cleared
     */
    public Field uponNoNature() {
        Field clone = this.clone();
        clone.nature = null;
        return clone;
    }

    /**
     * Returns a cloned field with the given size.
     *
     * @param size the replacement size
     * @return a cloned field with the size updated
     */
    public Field uponSize(Integer size) {
        Field clone = this.clone();
        clone.size = size;
        return clone;
    }

    /**
     * Returns a cloned field without a size.
     *
     * @return a cloned field with the size cleared
     */
    public Field uponNoSize() {
        Field clone = this.clone();
        clone.size = null;
        return clone;
    }

    /**
     * Returns a cloned field with the given precision.
     *
     * @param precision the replacement precision
     * @return a cloned field with the precision updated
     */
    public Field uponPrecision(Integer precision) {
        Field clone = this.clone();
        clone.precision = precision;
        return clone;
    }

    /**
     * Returns a cloned field without precision.
     *
     * @return a cloned field with the precision cleared
     */
    public Field uponNoPrecision() {
        Field clone = this.clone();
        clone.precision = null;
        return clone;
    }

    /**
     * Returns a cloned field with the given nullability flag.
     *
     * @param notNull the replacement nullability flag
     * @return a cloned field with the flag updated
     */
    public Field uponNotNull(Boolean notNull) {
        Field clone = this.clone();
        clone.notNull = notNull;
        return clone;
    }

    /**
     * Returns a cloned field without a nullability flag.
     *
     * @return a cloned field with the flag cleared
     */
    public Field uponNoNotNull() {
        Field clone = this.clone();
        clone.notNull = null;
        return clone;
    }

    /**
     * Returns a cloned field with the given auto-increment flag.
     *
     * @param autoIncrement the replacement auto-increment flag
     * @return a cloned field with the flag updated
     */
    public Field uponAutoIncrement(Boolean autoIncrement) {
        Field clone = this.clone();
        clone.autoIncrement = autoIncrement;
        return clone;
    }

    /**
     * Returns a cloned field without an auto-increment flag.
     *
     * @return a cloned field with the flag cleared
     */
    public Field uponNoAutoIncrement() {
        Field clone = this.clone();
        clone.autoIncrement = null;
        return clone;
    }

    /**
     * Returns a cloned field with the given auto-generated flag.
     *
     * @param autoGenerated the replacement auto-generated flag
     * @return a cloned field with the flag updated
     */
    public Field uponAutoGenerated(Boolean autoGenerated) {
        Field clone = this.clone();
        clone.autoGenerated = autoGenerated;
        return clone;
    }

    /**
     * Returns a cloned field without an auto-generated flag.
     *
     * @return a cloned field with the flag cleared
     */
    public Field uponNoAutoGenerated() {
        Field clone = this.clone();
        clone.autoGenerated = null;
        return clone;
    }

    /**
     * Returns a cloned field with the given primary-key flag.
     *
     * @param keyPrimary the replacement primary-key flag
     * @return a cloned field with the flag updated
     */
    public Field uponKeyPrimary(Boolean keyPrimary) {
        Field clone = this.clone();
        clone.keyPrimary = keyPrimary;
        return clone;
    }

    /**
     * Returns a cloned field without a primary-key flag.
     *
     * @return a cloned field with the flag cleared
     */
    public Field uponNoKeyPrimary() {
        Field clone = this.clone();
        clone.keyPrimary = null;
        return clone;
    }

    /**
     * Returns a cloned field with the given table reference.
     *
     * @param table the replacement table
     * @return a cloned field with the table updated
     */
    public Field uponTable(Table table) {
        Field clone = this.clone();
        clone.table = table;
        return clone;
    }

    /**
     * Returns a cloned field without a table reference.
     *
     * @return a cloned field with the table cleared
     */
    public Field uponNoTable() {
        Field clone = this.clone();
        clone.table = null;
        return clone;
    }

    /**
     * Creates a deep clone of this field.
     *
     * @return a deep copy of this field
     */
    @Override
    public Field clone() {
        return (Field) this.deepClone();
    }

    /**
     * Compares this field to another object using deep structural equality.
     *
     * @param that the object to compare
     * @return {@code true} when both objects are deeply equal; otherwise {@code false}
     */
    @Override
    public boolean equals(Object that) {
        return this.deepEquals(that);
    }

    /**
     * Computes a deep structural hash code for this field.
     *
     * @return the deep hash value
     */
    @Override
    public int hashCode() {
        return this.deepHash();
    }

    /**
     * Serializes this field to JSON text.
     *
     * @return the JSON representation of this field
     */
    @Override
    public String toString() {
        return this.toChars();
    }

    /**
     * Deserializes JSON text into a field.
     *
     * @param chars the JSON text to parse
     * @return the parsed field
     */
    public static Field fromChars(String chars) {
        return Base.fromChars(chars, Field.class);
    }

    /**
     * Returns the cached table reference.
     *
     * @return the table reference, or {@code null}
     */
    public Table getTable() {
        return table;
    }

    /**
     * Updates the cached table reference.
     *
     * @param table the new table reference
     */
    public void setTable(Table table) {
        this.table = table;
    }

    /**
     * Returns the field name qualified by its table reference when available.
     *
     * @return the reference name
     */
    public String getReferenceName() {
        return table != null ? table.getReferenceName() + "." + name : name;
    }

    /**
     * Converts this field to a typed descriptor.
     *
     * @return the typed descriptor
     */
    public Typed toTyped() {
        return new Typed(getReferenceName(), nature);
    }

    /**
     * Converts this field to a typed descriptor with an alias.
     *
     * @param alias the alias to apply
     * @return the typed descriptor
     */
    public Typed toTyped(String alias) {
        return new Typed(getReferenceName(), nature, alias);
    }

    /**
     * Converts this field to a valued descriptor without a value.
     *
     * @return the valued descriptor
     */
    public Valued toValued() {
        return new Valued(getReferenceName(), nature);
    }

    /**
     * Converts this field to a valued descriptor with the given value.
     *
     * @param value the value to store
     * @return the valued descriptor
     */
    public Valued toValued(Object value) {
        return new Valued(getReferenceName(), nature, value);
    }

    /**
     * Converts this field to a filter targeting the field name.
     *
     * @return the filter descriptor
     */
    public Filter toFilter() {
        return new Filter().withField(this);
    }

    /**
     * Formats a value according to this field type.
     *
     * @param value the value to format
     * @return the formatted text
     * @throws Exception if formatting fails
     */
    public String toFormatted(Object value) throws Exception {
        return WizData.toFormatted(this.nature, value);
    }

    /**
     * Parses formatted text into the requested type using this field type.
     *
     * @param formatted the formatted text
     * @param onClass the target class
     * @param <T> the result type
     * @return the parsed value
     * @throws Exception if parsing fails
     */
    public <T> T fromFormatted(String formatted, Class<T> onClass) throws Exception {
        return WizData.fromFormatted(this.nature, formatted, onClass);
    }
    
    /**
     * Parses formatted text into a value using this field type.
     *
     * @param formatted the formatted text
     * @return the parsed value
     * @throws Exception if parsing fails
     */
    public Object fromFormatted(String formatted) throws Exception {
        return WizData.fromFormatted(this.nature, formatted);
    }
    
}
